// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dmp_service.proto

package ads;

public final class DmpService {
  private DmpService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PageAttributeRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes id = 1;
    /**
     * <code>optional bytes id = 1;</code>
     *
     * <pre>
     * search id
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional bytes id = 1;</code>
     *
     * <pre>
     * search id
     * </pre>
     */
    com.google.protobuf.ByteString getId();

    // optional string page_id = 2;
    /**
     * <code>optional string page_id = 2;</code>
     *
     * <pre>
     * page id
     * </pre>
     */
    boolean hasPageId();
    /**
     * <code>optional string page_id = 2;</code>
     *
     * <pre>
     * page id
     * </pre>
     */
    String getPageId();
    /**
     * <code>optional string page_id = 2;</code>
     *
     * <pre>
     * page id
     * </pre>
     */
    com.google.protobuf.ByteString
        getPageIdBytes();

    // optional string url = 3;
    /**
     * <code>optional string url = 3;</code>
     *
     * <pre>
     * page url
     * </pre>
     */
    boolean hasUrl();
    /**
     * <code>optional string url = 3;</code>
     *
     * <pre>
     * page url
     * </pre>
     */
    String getUrl();
    /**
     * <code>optional string url = 3;</code>
     *
     * <pre>
     * page url
     * </pre>
     */
    com.google.protobuf.ByteString
        getUrlBytes();
  }
  /**
   * Protobuf type {@code ads.PageAttributeRequest}
   */
  public static final class PageAttributeRequest extends
      com.google.protobuf.GeneratedMessage
      implements PageAttributeRequestOrBuilder {
    // Use PageAttributeRequest.newBuilder() to construct.
    private PageAttributeRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PageAttributeRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PageAttributeRequest defaultInstance;
    public static PageAttributeRequest getDefaultInstance() {
      return defaultInstance;
    }

    public PageAttributeRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PageAttributeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              pageId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              url_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DmpService.internal_static_ads_PageAttributeRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DmpService.internal_static_ads_PageAttributeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PageAttributeRequest.class, Builder.class);
    }

    public static com.google.protobuf.Parser<PageAttributeRequest> PARSER =
        new com.google.protobuf.AbstractParser<PageAttributeRequest>() {
      public PageAttributeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PageAttributeRequest(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<PageAttributeRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString id_;
    /**
     * <code>optional bytes id = 1;</code>
     *
     * <pre>
     * search id
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes id = 1;</code>
     *
     * <pre>
     * search id
     * </pre>
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    // optional string page_id = 2;
    public static final int PAGE_ID_FIELD_NUMBER = 2;
    private Object pageId_;
    /**
     * <code>optional string page_id = 2;</code>
     *
     * <pre>
     * page id
     * </pre>
     */
    public boolean hasPageId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string page_id = 2;</code>
     *
     * <pre>
     * page id
     * </pre>
     */
    public String getPageId() {
      Object ref = pageId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pageId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string page_id = 2;</code>
     *
     * <pre>
     * page id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPageIdBytes() {
      Object ref = pageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string url = 3;
    public static final int URL_FIELD_NUMBER = 3;
    private Object url_;
    /**
     * <code>optional string url = 3;</code>
     *
     * <pre>
     * page url
     * </pre>
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string url = 3;</code>
     *
     * <pre>
     * page url
     * </pre>
     */
    public String getUrl() {
      Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string url = 3;</code>
     *
     * <pre>
     * page url
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = com.google.protobuf.ByteString.EMPTY;
      pageId_ = "";
      url_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPageIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getUrlBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPageIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getUrlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PageAttributeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PageAttributeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PageAttributeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PageAttributeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PageAttributeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PageAttributeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PageAttributeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PageAttributeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PageAttributeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PageAttributeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PageAttributeRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ads.PageAttributeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PageAttributeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DmpService.internal_static_ads_PageAttributeRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DmpService.internal_static_ads_PageAttributeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PageAttributeRequest.class, Builder.class);
      }

      // Construct using ads.DmpService.PageAttributeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        pageId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DmpService.internal_static_ads_PageAttributeRequest_descriptor;
      }

      public PageAttributeRequest getDefaultInstanceForType() {
        return PageAttributeRequest.getDefaultInstance();
      }

      public PageAttributeRequest build() {
        PageAttributeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PageAttributeRequest buildPartial() {
        PageAttributeRequest result = new PageAttributeRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pageId_ = pageId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.url_ = url_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PageAttributeRequest) {
          return mergeFrom((PageAttributeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PageAttributeRequest other) {
        if (other == PageAttributeRequest.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPageId()) {
          bitField0_ |= 0x00000002;
          pageId_ = other.pageId_;
          onChanged();
        }
        if (other.hasUrl()) {
          bitField0_ |= 0x00000004;
          url_ = other.url_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PageAttributeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PageAttributeRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes id = 1;
      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes id = 1;</code>
       *
       * <pre>
       * search id
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes id = 1;</code>
       *
       * <pre>
       * search id
       * </pre>
       */
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <code>optional bytes id = 1;</code>
       *
       * <pre>
       * search id
       * </pre>
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes id = 1;</code>
       *
       * <pre>
       * search id
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }

      // optional string page_id = 2;
      private Object pageId_ = "";
      /**
       * <code>optional string page_id = 2;</code>
       *
       * <pre>
       * page id
       * </pre>
       */
      public boolean hasPageId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string page_id = 2;</code>
       *
       * <pre>
       * page id
       * </pre>
       */
      public String getPageId() {
        Object ref = pageId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pageId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string page_id = 2;</code>
       *
       * <pre>
       * page id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPageIdBytes() {
        Object ref = pageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string page_id = 2;</code>
       *
       * <pre>
       * page id
       * </pre>
       */
      public Builder setPageId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string page_id = 2;</code>
       *
       * <pre>
       * page id
       * </pre>
       */
      public Builder clearPageId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pageId_ = getDefaultInstance().getPageId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string page_id = 2;</code>
       *
       * <pre>
       * page id
       * </pre>
       */
      public Builder setPageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pageId_ = value;
        onChanged();
        return this;
      }

      // optional string url = 3;
      private Object url_ = "";
      /**
       * <code>optional string url = 3;</code>
       *
       * <pre>
       * page url
       * </pre>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string url = 3;</code>
       *
       * <pre>
       * page url
       * </pre>
       */
      public String getUrl() {
        Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string url = 3;</code>
       *
       * <pre>
       * page url
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string url = 3;</code>
       *
       * <pre>
       * page url
       * </pre>
       */
      public Builder setUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 3;</code>
       *
       * <pre>
       * page url
       * </pre>
       */
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000004);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 3;</code>
       *
       * <pre>
       * page url
       * </pre>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        url_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ads.PageAttributeRequest)
    }

    static {
      defaultInstance = new PageAttributeRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ads.PageAttributeRequest)
  }

  public interface PageAttributeResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .cm.Keyword page_keyword = 1;
    /**
     * <code>repeated .cm.Keyword page_keyword = 1;</code>
     *
     * <pre>
     * keyword list
     * </pre>
     */
    java.util.List<cm.CommonTypes.Keyword> 
        getPageKeywordList();
    /**
     * <code>repeated .cm.Keyword page_keyword = 1;</code>
     *
     * <pre>
     * keyword list
     * </pre>
     */
    cm.CommonTypes.Keyword getPageKeyword(int index);
    /**
     * <code>repeated .cm.Keyword page_keyword = 1;</code>
     *
     * <pre>
     * keyword list
     * </pre>
     */
    int getPageKeywordCount();
    /**
     * <code>repeated .cm.Keyword page_keyword = 1;</code>
     *
     * <pre>
     * keyword list
     * </pre>
     */
    java.util.List<? extends cm.CommonTypes.KeywordOrBuilder> 
        getPageKeywordOrBuilderList();
    /**
     * <code>repeated .cm.Keyword page_keyword = 1;</code>
     *
     * <pre>
     * keyword list
     * </pre>
     */
    cm.CommonTypes.KeywordOrBuilder getPageKeywordOrBuilder(
            int index);

    // repeated .cm.PageTagType page_tag = 2;
    /**
     * <code>repeated .cm.PageTagType page_tag = 2;</code>
     *
     * <pre>
     * page tag
     * </pre>
     */
    java.util.List<cm.CommonTypes.PageTagType> getPageTagList();
    /**
     * <code>repeated .cm.PageTagType page_tag = 2;</code>
     *
     * <pre>
     * page tag
     * </pre>
     */
    int getPageTagCount();
    /**
     * <code>repeated .cm.PageTagType page_tag = 2;</code>
     *
     * <pre>
     * page tag
     * </pre>
     */
    cm.CommonTypes.PageTagType getPageTag(int index);
  }
  /**
   * Protobuf type {@code ads.PageAttributeResponse}
   */
  public static final class PageAttributeResponse extends
      com.google.protobuf.GeneratedMessage
      implements PageAttributeResponseOrBuilder {
    // Use PageAttributeResponse.newBuilder() to construct.
    private PageAttributeResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PageAttributeResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PageAttributeResponse defaultInstance;
    public static PageAttributeResponse getDefaultInstance() {
      return defaultInstance;
    }

    public PageAttributeResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PageAttributeResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                pageKeyword_ = new java.util.ArrayList<cm.CommonTypes.Keyword>();
                mutable_bitField0_ |= 0x00000001;
              }
              pageKeyword_.add(input.readMessage(cm.CommonTypes.Keyword.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              cm.CommonTypes.PageTagType value = cm.CommonTypes.PageTagType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  pageTag_ = new java.util.ArrayList<cm.CommonTypes.PageTagType>();
                  mutable_bitField0_ |= 0x00000002;
                }
                pageTag_.add(value);
              }
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                cm.CommonTypes.PageTagType value = cm.CommonTypes.PageTagType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                    pageTag_ = new java.util.ArrayList<cm.CommonTypes.PageTagType>();
                    mutable_bitField0_ |= 0x00000002;
                  }
                  pageTag_.add(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          pageKeyword_ = java.util.Collections.unmodifiableList(pageKeyword_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          pageTag_ = java.util.Collections.unmodifiableList(pageTag_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DmpService.internal_static_ads_PageAttributeResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DmpService.internal_static_ads_PageAttributeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PageAttributeResponse.class, Builder.class);
    }

    public static com.google.protobuf.Parser<PageAttributeResponse> PARSER =
        new com.google.protobuf.AbstractParser<PageAttributeResponse>() {
      public PageAttributeResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PageAttributeResponse(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<PageAttributeResponse> getParserForType() {
      return PARSER;
    }

    // repeated .cm.Keyword page_keyword = 1;
    public static final int PAGE_KEYWORD_FIELD_NUMBER = 1;
    private java.util.List<cm.CommonTypes.Keyword> pageKeyword_;
    /**
     * <code>repeated .cm.Keyword page_keyword = 1;</code>
     *
     * <pre>
     * keyword list
     * </pre>
     */
    public java.util.List<cm.CommonTypes.Keyword> getPageKeywordList() {
      return pageKeyword_;
    }
    /**
     * <code>repeated .cm.Keyword page_keyword = 1;</code>
     *
     * <pre>
     * keyword list
     * </pre>
     */
    public java.util.List<? extends cm.CommonTypes.KeywordOrBuilder> 
        getPageKeywordOrBuilderList() {
      return pageKeyword_;
    }
    /**
     * <code>repeated .cm.Keyword page_keyword = 1;</code>
     *
     * <pre>
     * keyword list
     * </pre>
     */
    public int getPageKeywordCount() {
      return pageKeyword_.size();
    }
    /**
     * <code>repeated .cm.Keyword page_keyword = 1;</code>
     *
     * <pre>
     * keyword list
     * </pre>
     */
    public cm.CommonTypes.Keyword getPageKeyword(int index) {
      return pageKeyword_.get(index);
    }
    /**
     * <code>repeated .cm.Keyword page_keyword = 1;</code>
     *
     * <pre>
     * keyword list
     * </pre>
     */
    public cm.CommonTypes.KeywordOrBuilder getPageKeywordOrBuilder(
        int index) {
      return pageKeyword_.get(index);
    }

    // repeated .cm.PageTagType page_tag = 2;
    public static final int PAGE_TAG_FIELD_NUMBER = 2;
    private java.util.List<cm.CommonTypes.PageTagType> pageTag_;
    /**
     * <code>repeated .cm.PageTagType page_tag = 2;</code>
     *
     * <pre>
     * page tag
     * </pre>
     */
    public java.util.List<cm.CommonTypes.PageTagType> getPageTagList() {
      return pageTag_;
    }
    /**
     * <code>repeated .cm.PageTagType page_tag = 2;</code>
     *
     * <pre>
     * page tag
     * </pre>
     */
    public int getPageTagCount() {
      return pageTag_.size();
    }
    /**
     * <code>repeated .cm.PageTagType page_tag = 2;</code>
     *
     * <pre>
     * page tag
     * </pre>
     */
    public cm.CommonTypes.PageTagType getPageTag(int index) {
      return pageTag_.get(index);
    }

    private void initFields() {
      pageKeyword_ = java.util.Collections.emptyList();
      pageTag_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < pageKeyword_.size(); i++) {
        output.writeMessage(1, pageKeyword_.get(i));
      }
      for (int i = 0; i < pageTag_.size(); i++) {
        output.writeEnum(2, pageTag_.get(i).getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < pageKeyword_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, pageKeyword_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < pageTag_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(pageTag_.get(i).getNumber());
        }
        size += dataSize;
        size += 1 * pageTag_.size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PageAttributeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PageAttributeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PageAttributeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PageAttributeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PageAttributeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PageAttributeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PageAttributeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PageAttributeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PageAttributeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PageAttributeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PageAttributeResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ads.PageAttributeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PageAttributeResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DmpService.internal_static_ads_PageAttributeResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DmpService.internal_static_ads_PageAttributeResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PageAttributeResponse.class, Builder.class);
      }

      // Construct using ads.DmpService.PageAttributeResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPageKeywordFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (pageKeywordBuilder_ == null) {
          pageKeyword_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pageKeywordBuilder_.clear();
        }
        pageTag_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DmpService.internal_static_ads_PageAttributeResponse_descriptor;
      }

      public PageAttributeResponse getDefaultInstanceForType() {
        return PageAttributeResponse.getDefaultInstance();
      }

      public PageAttributeResponse build() {
        PageAttributeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PageAttributeResponse buildPartial() {
        PageAttributeResponse result = new PageAttributeResponse(this);
        int from_bitField0_ = bitField0_;
        if (pageKeywordBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            pageKeyword_ = java.util.Collections.unmodifiableList(pageKeyword_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.pageKeyword_ = pageKeyword_;
        } else {
          result.pageKeyword_ = pageKeywordBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          pageTag_ = java.util.Collections.unmodifiableList(pageTag_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.pageTag_ = pageTag_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PageAttributeResponse) {
          return mergeFrom((PageAttributeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PageAttributeResponse other) {
        if (other == PageAttributeResponse.getDefaultInstance()) return this;
        if (pageKeywordBuilder_ == null) {
          if (!other.pageKeyword_.isEmpty()) {
            if (pageKeyword_.isEmpty()) {
              pageKeyword_ = other.pageKeyword_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePageKeywordIsMutable();
              pageKeyword_.addAll(other.pageKeyword_);
            }
            onChanged();
          }
        } else {
          if (!other.pageKeyword_.isEmpty()) {
            if (pageKeywordBuilder_.isEmpty()) {
              pageKeywordBuilder_.dispose();
              pageKeywordBuilder_ = null;
              pageKeyword_ = other.pageKeyword_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pageKeywordBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPageKeywordFieldBuilder() : null;
            } else {
              pageKeywordBuilder_.addAllMessages(other.pageKeyword_);
            }
          }
        }
        if (!other.pageTag_.isEmpty()) {
          if (pageTag_.isEmpty()) {
            pageTag_ = other.pageTag_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePageTagIsMutable();
            pageTag_.addAll(other.pageTag_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PageAttributeResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PageAttributeResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .cm.Keyword page_keyword = 1;
      private java.util.List<cm.CommonTypes.Keyword> pageKeyword_ =
        java.util.Collections.emptyList();
      private void ensurePageKeywordIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          pageKeyword_ = new java.util.ArrayList<cm.CommonTypes.Keyword>(pageKeyword_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          cm.CommonTypes.Keyword, cm.CommonTypes.Keyword.Builder, cm.CommonTypes.KeywordOrBuilder> pageKeywordBuilder_;

      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public java.util.List<cm.CommonTypes.Keyword> getPageKeywordList() {
        if (pageKeywordBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pageKeyword_);
        } else {
          return pageKeywordBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public int getPageKeywordCount() {
        if (pageKeywordBuilder_ == null) {
          return pageKeyword_.size();
        } else {
          return pageKeywordBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public cm.CommonTypes.Keyword getPageKeyword(int index) {
        if (pageKeywordBuilder_ == null) {
          return pageKeyword_.get(index);
        } else {
          return pageKeywordBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public Builder setPageKeyword(
          int index, cm.CommonTypes.Keyword value) {
        if (pageKeywordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePageKeywordIsMutable();
          pageKeyword_.set(index, value);
          onChanged();
        } else {
          pageKeywordBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public Builder setPageKeyword(
          int index, cm.CommonTypes.Keyword.Builder builderForValue) {
        if (pageKeywordBuilder_ == null) {
          ensurePageKeywordIsMutable();
          pageKeyword_.set(index, builderForValue.build());
          onChanged();
        } else {
          pageKeywordBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public Builder addPageKeyword(cm.CommonTypes.Keyword value) {
        if (pageKeywordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePageKeywordIsMutable();
          pageKeyword_.add(value);
          onChanged();
        } else {
          pageKeywordBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public Builder addPageKeyword(
          int index, cm.CommonTypes.Keyword value) {
        if (pageKeywordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePageKeywordIsMutable();
          pageKeyword_.add(index, value);
          onChanged();
        } else {
          pageKeywordBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public Builder addPageKeyword(
          cm.CommonTypes.Keyword.Builder builderForValue) {
        if (pageKeywordBuilder_ == null) {
          ensurePageKeywordIsMutable();
          pageKeyword_.add(builderForValue.build());
          onChanged();
        } else {
          pageKeywordBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public Builder addPageKeyword(
          int index, cm.CommonTypes.Keyword.Builder builderForValue) {
        if (pageKeywordBuilder_ == null) {
          ensurePageKeywordIsMutable();
          pageKeyword_.add(index, builderForValue.build());
          onChanged();
        } else {
          pageKeywordBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public Builder addAllPageKeyword(
          Iterable<? extends cm.CommonTypes.Keyword> values) {
        if (pageKeywordBuilder_ == null) {
          ensurePageKeywordIsMutable();
          super.addAll(values, pageKeyword_);
          onChanged();
        } else {
          pageKeywordBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public Builder clearPageKeyword() {
        if (pageKeywordBuilder_ == null) {
          pageKeyword_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pageKeywordBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public Builder removePageKeyword(int index) {
        if (pageKeywordBuilder_ == null) {
          ensurePageKeywordIsMutable();
          pageKeyword_.remove(index);
          onChanged();
        } else {
          pageKeywordBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public cm.CommonTypes.Keyword.Builder getPageKeywordBuilder(
          int index) {
        return getPageKeywordFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public cm.CommonTypes.KeywordOrBuilder getPageKeywordOrBuilder(
          int index) {
        if (pageKeywordBuilder_ == null) {
          return pageKeyword_.get(index);  } else {
          return pageKeywordBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public java.util.List<? extends cm.CommonTypes.KeywordOrBuilder> 
           getPageKeywordOrBuilderList() {
        if (pageKeywordBuilder_ != null) {
          return pageKeywordBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pageKeyword_);
        }
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public cm.CommonTypes.Keyword.Builder addPageKeywordBuilder() {
        return getPageKeywordFieldBuilder().addBuilder(
            cm.CommonTypes.Keyword.getDefaultInstance());
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public cm.CommonTypes.Keyword.Builder addPageKeywordBuilder(
          int index) {
        return getPageKeywordFieldBuilder().addBuilder(
            index, cm.CommonTypes.Keyword.getDefaultInstance());
      }
      /**
       * <code>repeated .cm.Keyword page_keyword = 1;</code>
       *
       * <pre>
       * keyword list
       * </pre>
       */
      public java.util.List<cm.CommonTypes.Keyword.Builder> 
           getPageKeywordBuilderList() {
        return getPageKeywordFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          cm.CommonTypes.Keyword, cm.CommonTypes.Keyword.Builder, cm.CommonTypes.KeywordOrBuilder> 
          getPageKeywordFieldBuilder() {
        if (pageKeywordBuilder_ == null) {
          pageKeywordBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              cm.CommonTypes.Keyword, cm.CommonTypes.Keyword.Builder, cm.CommonTypes.KeywordOrBuilder>(
                  pageKeyword_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          pageKeyword_ = null;
        }
        return pageKeywordBuilder_;
      }

      // repeated .cm.PageTagType page_tag = 2;
      private java.util.List<cm.CommonTypes.PageTagType> pageTag_ =
        java.util.Collections.emptyList();
      private void ensurePageTagIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          pageTag_ = new java.util.ArrayList<cm.CommonTypes.PageTagType>(pageTag_);
          bitField0_ |= 0x00000002;
        }
      }
      /**
       * <code>repeated .cm.PageTagType page_tag = 2;</code>
       *
       * <pre>
       * page tag
       * </pre>
       */
      public java.util.List<cm.CommonTypes.PageTagType> getPageTagList() {
        return java.util.Collections.unmodifiableList(pageTag_);
      }
      /**
       * <code>repeated .cm.PageTagType page_tag = 2;</code>
       *
       * <pre>
       * page tag
       * </pre>
       */
      public int getPageTagCount() {
        return pageTag_.size();
      }
      /**
       * <code>repeated .cm.PageTagType page_tag = 2;</code>
       *
       * <pre>
       * page tag
       * </pre>
       */
      public cm.CommonTypes.PageTagType getPageTag(int index) {
        return pageTag_.get(index);
      }
      /**
       * <code>repeated .cm.PageTagType page_tag = 2;</code>
       *
       * <pre>
       * page tag
       * </pre>
       */
      public Builder setPageTag(
          int index, cm.CommonTypes.PageTagType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePageTagIsMutable();
        pageTag_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .cm.PageTagType page_tag = 2;</code>
       *
       * <pre>
       * page tag
       * </pre>
       */
      public Builder addPageTag(cm.CommonTypes.PageTagType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePageTagIsMutable();
        pageTag_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .cm.PageTagType page_tag = 2;</code>
       *
       * <pre>
       * page tag
       * </pre>
       */
      public Builder addAllPageTag(
          Iterable<? extends cm.CommonTypes.PageTagType> values) {
        ensurePageTagIsMutable();
        super.addAll(values, pageTag_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .cm.PageTagType page_tag = 2;</code>
       *
       * <pre>
       * page tag
       * </pre>
       */
      public Builder clearPageTag() {
        pageTag_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ads.PageAttributeResponse)
    }

    static {
      defaultInstance = new PageAttributeResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ads.PageAttributeResponse)
  }

  /**
   * Protobuf service {@code ads.PageAttributeService}
   */
  public static abstract class PageAttributeService
      implements com.google.protobuf.Service {
    protected PageAttributeService() {}

    public interface Interface {
      /**
       * <code>rpc search(.ads.PageAttributeRequest) returns (.ads.PageAttributeResponse);</code>
       */
      public abstract void search(
              com.google.protobuf.RpcController controller,
              PageAttributeRequest request,
              com.google.protobuf.RpcCallback<PageAttributeResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new PageAttributeService() {
        @Override
        public  void search(
            com.google.protobuf.RpcController controller,
            PageAttributeRequest request,
            com.google.protobuf.RpcCallback<PageAttributeResponse> done) {
          impl.search(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.search(controller, (PageAttributeRequest)request);
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return PageAttributeRequest.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return PageAttributeResponse.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc search(.ads.PageAttributeRequest) returns (.ads.PageAttributeResponse);</code>
     */
    public abstract void search(
        com.google.protobuf.RpcController controller,
        PageAttributeRequest request,
        com.google.protobuf.RpcCallback<PageAttributeResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return DmpService.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.search(controller, (PageAttributeRequest)request,
            com.google.protobuf.RpcUtil.<PageAttributeResponse>specializeCallback(
              done));
          return;
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return PageAttributeRequest.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return PageAttributeResponse.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends PageAttributeService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void search(
          com.google.protobuf.RpcController controller,
          PageAttributeRequest request,
          com.google.protobuf.RpcCallback<PageAttributeResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          PageAttributeResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            PageAttributeResponse.class,
            PageAttributeResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public PageAttributeResponse search(
              com.google.protobuf.RpcController controller,
              PageAttributeRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public PageAttributeResponse search(
          com.google.protobuf.RpcController controller,
          PageAttributeRequest request)
          throws com.google.protobuf.ServiceException {
        return (PageAttributeResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          PageAttributeResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:ads.PageAttributeService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ads_PageAttributeRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ads_PageAttributeRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ads_PageAttributeResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ads_PageAttributeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021dmp_service.proto\022\003ads\032\022common_types.p" +
      "roto\"@\n\024PageAttributeRequest\022\n\n\002id\030\001 \001(\014" +
      "\022\017\n\007page_id\030\002 \001(\t\022\013\n\003url\030\003 \001(\t\"]\n\025PageAt" +
      "tributeResponse\022!\n\014page_keyword\030\001 \003(\0132\013." +
      "cm.Keyword\022!\n\010page_tag\030\002 \003(\0162\017.cm.PageTa" +
      "gType2W\n\024PageAttributeService\022?\n\006search\022" +
      "\031.ads.PageAttributeRequest\032\032.ads.PageAtt" +
      "ributeResponseB\006\200\001\001\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ads_PageAttributeRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ads_PageAttributeRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ads_PageAttributeRequest_descriptor,
              new String[] { "Id", "PageId", "Url", });
          internal_static_ads_PageAttributeResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ads_PageAttributeResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ads_PageAttributeResponse_descriptor,
              new String[] { "PageKeyword", "PageTag", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cm.CommonTypes.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
